# Generated by Django 2.2.7 on 2021-05-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosyrienapp', '0003_auto_20200430_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refugees2011',
            options={'verbose_name_plural': 'Refugees2011'},
        ),
        migrations.AlterModelOptions(
            name='refugees2012',
            options={'verbose_name_plural': 'Refugees2012'},
        ),
        migrations.AlterModelOptions(
            name='refugees2013',
            options={'verbose_name_plural': 'Refugees2013'},
        ),
        migrations.AlterModelOptions(
            name='refugees2014',
            options={'verbose_name_plural': 'Refugees2014'},
        ),
        migrations.AlterModelOptions(
            name='refugees2015',
            options={'verbose_name_plural': 'Refugees2015'},
        ),
        migrations.AlterModelOptions(
            name='refugees2016',
            options={'verbose_name_plural': 'Refugees2016'},
        ),
        migrations.AlterModelOptions(
            name='refugees2017',
            options={'verbose_name_plural': 'Refugees2017'},
        ),
        migrations.AlterModelOptions(
            name='refugees2018',
            options={'verbose_name_plural': 'Refugees2018'},
        ),
    ]
